server:
  port: 8081
spring:
  rabbitmq:
    port: 8086
#Database things
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    name: demo
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
rabbit:
  exchange: "skt_demo_exchange"
  queue:
    save: "save_queue"
    show: "show_queue"
    show-answer: "show_answer_queue"
    save-answer: "save_answer_queue"
  routing-key:
    save: "save_routingKey"
    show: "show_routingKey"
    show-answer: "show_answer_routingKey"
    save-answer: "save_answer_routingKey"
