server:
  port: 8081
spring:
  rabbitmq:
    port: 8086
#Database things
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    name: demo
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
rabbit:
  exchange: "skt_demo_exchange"
  queue:
    save: "save_queue"
    show: "show_queue"
    show_answer: "show_answer_queue"
    save_answer: "save_answer_queue"
  routing_key:
    save: "save_routingKey"
    show: "show_routingKey"
    show_answer: "show_answer_routingKey"
    save_answer: "save_answer_routingKey"
